language: erlang

sudo: false

otp_release:
  - 17.5
  - 18.3
  - 19.0

notifications:
  email: false

cache:
  directories:
    - llvm-3.7.1

env:
  global:
    - LLVM_VERSION=3.7.1
    - CC=clang
    - CXX=clang++
    - ARCHFLAGS=-Wgcc-compat

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ -z "$(ls -A llvm-$LLVM_VERSION)" ]; then
        wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
        mkdir llvm-$LLVM_VERSION;
        xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
      fi;
      llvm-$LLVM_VERSION/bin/llvm-config --version;
      export LLVM_CONFIG="llvm-$LLVM_VERSION/bin/llvm-config";
      export PATH="$HOME/llvm-$LLVM_VERSION/bin:$PATH";
    fi

script:
  - "make tests"