language: erlang

sudo: false

otp_release:
  - 17.5
  - 18.0
  - 18.2

notifications:
  email: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6

env:
  - CC=clang-3.6 CXX=clang++-3.6

script:
  - "make tests"
