language: erlang

sudo: false

otp_release:
  - 17.5
  - 18.0
  - 18.2

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7

env:
  - CC=clang-3.7 CXX=clang++-3.7 ARCHFLAGS=-Wgcc-compat

script:
  - "make tests"
