language: generic

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=21.1.3

cache:
  directories:
    - docker-otp-21.1.3
    - test/fips180_4_SUITE_data/shabytetestvectors
    - test/fips202_SUITE_data/keccaktestvectors

before_install:
  - make docker-setup DOCKER_OTP_VERSION=${OTP_VERSION}

script:
  - make docker-test DOCKER_OTP_VERSION=${OTP_VERSION}
